version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: piiXELdb
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
  auth:
    build: ./services/auth
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=5001
      - JWT_SECRET=supersecretjwt
      - POSTGRES_URI=postgresql://user:password@postgres:5432/piiXELdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
