services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: piixel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  mongo_data:
